### ISSUE TITLE
Opening Manual Valve in Cavas

### ISSUE THREAD

**Issue by ael-noblegas** [aelamspychron/pychron#10]
active branch=dev/dc

active analyses=

description=""

Traceback
```
Traceback (most recent call last):
  File "C:\anaconda3\envs\pychron3\lib\site-packages\enable\qt4\base_window.py", line 237, in mousePressEvent
    self.handler.mousePressEvent(event)
  File "C:\anaconda3\envs\pychron3\lib\site-packages\enable\qt4\base_window.py", line 124, in mousePressEvent
    self._enable_window._handle_mouse_event(name + "_down", event)
  File "C:\anaconda3\envs\pychron3\lib\site-packages\enable\abstract_window.py", line 352, in _handle_mouse_event
    self.component.dispatch(mouse_event, event_name)
  File "C:\anaconda3\envs\pychron3\lib\site-packages\enable\component.py", line 921, in dispatch
    self._new_dispatch(event, suffix)
  File "C:\anaconda3\envs\pychron3\lib\site-packages\enable\component.py", line 961, in _new_dispatch
    self._dispatch_stateful_event(event, suffix)
  File "C:\anaconda3\envs\pychron3\lib\site-packages\enable\container.py", line 524, in _dispatch_stateful_event
    self._container_handle_mouse_event(event, suffix)
  File "C:\anaconda3\envs\pychron3\lib\site-packages\enable\container.py", line 427, in _container_handle_mouse_event
    Component._dispatch_stateful_event(self, event, suffix)
  File "C:\anaconda3\envs\pychron3\lib\site-packages\enable\interactor.py", line 110, in _dispatch_stateful_event
    handler(event)
  File "C:\Users\Science\.pychron.0\pychron\pychron\canvas\canvas2D\extraction_line_canvas2D.py", line 232, in select_left_down
    ok, change = self.manager.open_valve(item.name, mode=mode)
  File "C:\Users\Science\.pychron.0\pychron\pychron\extraction_line\extraction_line_manager.py", line 440, in open_valve
    return self._open_close_valve(name, 'open', **kw)
  File "C:\Users\Science\.pychron.0\pychron\pychron\extraction_line\extraction_line_manager.py", line 662, in _open_close_valve
    description = valve.description
AttributeError: 'NoneType' object has no attribute 'description'

```

**Comment by jirhiker** [comment]
issue resolved on NMGRL/dev/dc branch
