### ISSUE TITLE
Credential Error

### ISSUE THREAD

**Issue by ael-noblegas** [aelamspychron/pychron#12]
active branch=dev/dc

active analyses=

description="Received this error. Updated token. Still receiving error and the token its referencing in the error is the previous token."

Traceback
```
Traceback (most recent call last):
  File "C:\Anaconda3\envs\pychron3\lib\site-packages\traits\trait_notifiers.py", line 394, in __call__
    self.handler(*args)
  File "C:\Users\Science\.pychron.0\pychron\pychron\envisage\tasks\base_tasks_application.py", line 51, in _application_initialized_fired
    self.do_startup_tests()
  File "C:\Users\Science\.pychron.0\pychron\pychron\envisage\tasks\base_tasks_application.py", line 62, in do_startup_tests
    st.test_plugin(plugin)
  File "C:\Users\Science\.pychron.0\pychron\pychron\startup_test\tester.py", line 93, in test_plugin
    result=result)
  File "C:\Users\Science\.pychron.0\pychron\pychron\startup_test\tester.py", line 111, in add_test_result
    self.results.append(TestResult(**kw))
  File "C:\Anaconda3\envs\pychron3\lib\site-packages\traits\trait_handlers.py", line 236, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The 'error' trait of a TestResult instance must be a string, but a value of CredentialException({'Authorization': 'token 5ca4122efb3cfdd0b691f5286c8802f476043d2d'}) <class 'pychron.git.hosts.CredentialException'> was specified.

```

**Comment by jirhiker** [comment]
git config --global credential.helper wincred 

Credentials on windows not actually used from pychron/preferences. they are stored in the windows credential manager. need to set new token there

**Comment by ael-noblegas** [comment]
So when updating credentials, do I update it in both the .bat and windows manager?

**Comment by jirhiker** [comment]
update in both.

[It probably shouldn't be this way but it is currently...] 
the token in the windows manager is used by pychron data management system
the token in the .bat file is used to submit bugs

**Comment by ael-noblegas** [comment]
Updated win creds, bat, was still seeing that token in the error.

Turns out there was a third place.

![Git_Pref_SFT](https://user-images.githubusercontent.com/52926977/120828501-9ab84d00-c52a-11eb-9e09-6a0207ffb1b9.PNG)

Solved.

**Comment by ael-noblegas** [comment]
Updated win cred, bat, updated GIT as well. Was still seeing the old token in the error.

Turns out there was a third place.

![Git_Pref_SFT](https://user-images.githubusercontent.com/52926977/120828847-013d6b00-c52b-11eb-9e04-96a82b79c0e1.PNG)

Solved.
