### ISSUE TITLE
Attempted Magnet Scan

### ISSUE THREAD

**Issue by ael-noblegas** [aelamspychron/pychron#6]
active branch=dev/dc

active analyses=

description="Sleep length must be non-negative."

Traceback
```
Traceback (most recent call last):
  File "C:\Users\Science\.pychron.0\pychron\pychron\core\helpers\exception_helper.py", line 285, in run_with_except_hook
    run_old(*args, **kw)
  File "C:\Anaconda3\envs\pychron3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Science\.pychron.0\pychron\pychron\spectrometer\jobs\base_scanner.py", line 111, in _scan
    time.sleep(period)
ValueError: sleep length must be non-negative

```

**Comment by jirhiker** [comment]
increase your integration time or decrease the magnet settling time.  

```
        period = spec.integration_time - magnet.settling_time
        # period = 0.1
        st = time.time()

        limits = self._get_limits()
        graph.set_x_limits(*limits, pad='0.1')
        
        self.debug('reference detector {}'.format(spec.reference_detector))
        refdet = spec.get_detector(spec.reference_detector)

        for i, si in enumerate(self._calculate_steps(*limits)):
            if self._cancel_event.is_set():
                self.debug('exiting scan. dac={}'.format(si))
                break

            self._do_step(magnet, si)
            time.sleep(period)
```

magnet settling time defaults to 0.5seconds i think so setting integration time to 1sec should be sufficient
