### ISSUE TITLE
Heater Debugging

### ISSUE THREAD

**Issue by ael-noblegas** [aelamspychron/pychron#7]
active branch=dev/dc

active analyses=

description=""

Traceback
```
Traceback (most recent call last):
  File "C:\anaconda3\envs\pychron3\lib\site-packages\traits\trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "C:\Users\Science\.pychron.0\pychron\pychron\hardware\heater.py", line 65, in _onoff_button_fired
    self.set_active(self.onoff_state)
  File "C:\Users\Science\.pychron.0\pychron\pychron\hardware\heater.py", line 118, in set_active
    self._write_coil(self.enable_address, bool(state))
  File "C:\Users\Science\.pychron.0\pychron\pychron\hardware\core\modbus.py", line 44, in _write_coil
    return self._func('write_coil', *args, **kw)
  File "C:\Users\Science\.pychron.0\pychron\pychron\hardware\core\modbus.py", line 38, in _func
    return getattr(self.communicator, funcname)(*args, **kw)
  File "C:\anaconda3\envs\pychron3\lib\site-packages\pymodbus\client\common.py", line 70, in write_coil
    return self.execute(request)
  File "C:\anaconda3\envs\pychron3\lib\site-packages\pymodbus\client\sync.py", line 108, in execute
    return self.transaction.execute(request)
  File "C:\anaconda3\envs\pychron3\lib\site-packages\pymodbus\transaction.py", line 158, in execute
    broadcast=broadcast
  File "C:\anaconda3\envs\pychron3\lib\site-packages\pymodbus\transaction.py", line 228, in _transact
    packet = self.client.framer.buildPacket(packet)
  File "C:\anaconda3\envs\pychron3\lib\site-packages\pymodbus\framer\socket_framer.py", line 206, in buildPacket
    data = message.encode()
  File "C:\anaconda3\envs\pychron3\lib\site-packages\pymodbus\bit_write_message.py", line 58, in encode
    result  = struct.pack('>H', self.address)
struct.error: argument out of range

```

**Comment by jirhiker** [comment]
invalid `enable_address`
